image:
  repository: crpi-li78f6lp5zheaj11.cn-shenzhen.personal.cr.aliyuncs.com/pyclaw/pyclaw-web
  tag: 0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: aliyun-acr-pull-secret

backend:
  upstream: pyclaw-spring-backend.pyclaw.svc.cluster.local:8080

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: console.anxin-hitsz.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
