apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claw-saas-mysql.fullname" . }}-config
  labels:
    {{- include "claw-saas-mysql.labels" . | nindent 4 }}
data:
  claw-saas.cnf: |
    [mysqld]
    character-set-server={{ .Values.config.characterSetServer }}
    collation-server={{ .Values.config.collationServer }}
    {{- with .Values.config.extra }}
{{ . | indent 4 }}
    {{- end }}
